<?php
return [
    'adminEmail' => 'admin@example.com',
    'supportEmail' => 'support@example.com',
    'user.passwordResetTokenExpire' => 3600,
    'google-maps-api-key' => 'AIzaSyBgZX9Fm46KdlM3Fa7AY3INTORL92gf2lk',
    'marker-image' => '@web/images/marker.png',
    'profile_uploads_path'=>'@common/uploads/customer-photos/',
    'base_url'=>'http://139.162.54.79/wastemanagement/common/uploads/customer-photos/',
    'mrc_base_url'=>'http://139.162.54.79/wastemanagement/common/uploads/mrc/',
    'dumping_base_url'=>'http://139.162.54.79/wastemanagement/common/uploads/dumping-incidents/',
    'base_url_gt'=>'http://139.162.54.79/wastemanagement/common/uploads/gt/',
    'defaultImage'=> 'customer-photos/profile.png',
    'incident_image_uploads_path'=>'@common/uploads/incident-images/',
     'camera_image_uploads_path'=>'@common/uploads/camera-images/',
    'video_uploads_path'=>'@common/uploads/incident-videos/',
    'incident_image_base_url'=>'http://139.162.54.79/wastemanagement/common/uploads/incident-images/',
    'camera_image_base_url'=>'http://139.162.54.79/wastemanagement/common/uploads/camera-images/',
    'incident_video_base_url'=>'http://139.162.54.79/wastemanagement/common/uploads/incident-videos/',
    'incident_base' => 'http://139.162.54.79/wastemanagement/backend/web/incidents/incident-preview?id=',
    'invoice_base' => 'http://139.162.54.79/wastemanagement/backend/web/invoice/generate?id=',
    'signature_image_uploads_path'=>'@common/uploads/signature-images/',
    'signature_image_base_url' =>'/wastemanagement/common/uploads/signature-images/',
    'posts_image_base_url' =>'/wastemanagement/common/uploads/posts/',
    'logo_image_base_url' =>'/wastemanagement/common/uploads/logo/',
    'home_image_base_url' =>'/wastemanagement/common/uploads/home/',
    'logo_image_base_urls'=>'@common/uploads/logo/',
    'posts_image_base_urls'=>'@common/uploads/posts/',
    'home_image_base_urls'=>'@common/uploads/home/',
    'dumping_base_urls'=>'@common/uploads/dumping-incidents/',
    'mrc_base_urls'=>'@common/uploads/mrc/',
    'camera_service_image_uploads_path' =>'@common/uploads/camera-service-images/',
    'camera_service_image_base_url' =>'http://139.162.54.79/development/wastemanagement/common/uploads/camera-service-images/',
    'image_base'=>'@common/uploads/',
    'image_base_logo'=>'@common/uploads/logo',
    'authKey' => 'AIzaSyAX8tFIBJBpWcyaYHscZrEDcWa3Kp2V7mI',
    'settingsId'=> 1,
    'backend_public_url'=>'http://portal.greentrivandrum.in/',
    'authKeyMsg'=>'283326AYHR8CW2Rakl5d19b46c',
     'back_up_url'=>'@common/backup/',
];
